version: "3.3"
services:
   ms_mail_server:
      stdin_open: true
      tty: true
      build: 
         context: ./
         dockerfile: ms_mail_server/DockerFile
      container_name: ms_mail_server     
      depends_on:
         - ms_mysql_master
      # links:
      #    - ms_mysql_master:ms_mysql_master
      #volumes:
      #   - "${VOLUMES_BASE}/etc/letsencrypt:/etc/letsencrypt"
      ports:
         - "25:25"
         - "587:587"
         - "465:465"
         - "143:143"
         - "993:993"
         - "110:110"
         - "995:995"         
      expose:
         - "80"
         - "443"
         - "25"
         - "587"
         - "465"
         - "143"
         - "993"
         - "110"
         - "995"

      networks:
         ms_net:
            ipv4_address: 172.19.0.2
      environment:
         MYSQL_MASTER_ROOT_PASSWORD: ${MYSQL_MASTER_ROOT_PASSWORD}
         MYSQL_MASTER_DATABASE: ${MYSQL_MASTER_DATABASE}
         MYSQL_MASTER_USER: ${MYSQL_MASTER_USER}
         MYSQL_MASTER_PASSWORD: ${MYSQL_MASTER_PASSWORD}
         MYSQL_MASTER_HOST: ${MYSQL_MASTER_HOST}
         MAIL_SERVER_DOMAIN: ${MAIL_SERVER_DOMAIN}
         MAIL_SERVER_HOST: ${MAIL_SERVER_HOST}
         MAIL_ADMIN_HOST: ${MAIL_ADMIN_HOST}
         MAIL_HOST: ${MAIL_HOST}

      extra_hosts:
         - "ms_mysql_master:172.19.0.3"
      restart: always
      #privileged: true
      #user: root
      command: ["/usr/bin/startup"]
   
   ms_mysql_master:
      stdin_open: true
      tty: true 
      build:
         context: ./
         dockerfile: ms_mysql_master/DockerFile
      container_name: ms_mysql_master
      ports:
         - "53306:3306"
      volumes:
         - "${VOLUMES_BASE}/var/lib/mysql:/var/lib/mysql"
      environment:
         - MYSQL_ROOT_PASSWORD=${MYSQL_MASTER_ROOT_PASSWORD}
      networks:
         ms_net:
            ipv4_address: 172.19.0.3
      restart: always

networks:
   ms_net:
      driver: bridge
      name: ms_net
      ipam:
         driver: default
         config:
            - subnet: "172.19.0.0/24"
              gateway: "172.19.0.1"
              
      
