DROP DATABASE IF EXISTS <MYSQL_MASTER_DATABASE>;
CREATE DATABASE <MYSQL_MASTER_DATABASE> CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE <MYSQL_MASTER_DATABASE>;
-- CREATE USER 'mail'@'localhost' IDENTIFIED WITH caching_sha2_password BY 'dbpassword';
CREATE USER '<MYSQL_MASTER_USER>'@'<MYSQL_MASTER_HOST>' IDENTIFIED WITH  BY '<MYSQL_MASTER_PASSWORD>';
-- GRANT ALL PRIVILEGES ON <MYSQL_MASTER_DATABASE>.* TO '<MYSQL_MASTER_USER>'@'<MYSQL_MASTER_HOST>';
GRANT SELECT ,INSERT ,UPDATE ,DELETE ON <MYSQL_MASTER_DATABASE>.* TO '<MYSQL_MASTER_USER>'@'<MYSQL_MASTER_HOST>';
FLUSH PRIVILEGES;